name: tests

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build extension
        run: yarn compile
      - name: Install PlaydateSDK (macOS)
        run: ./scripts/installSDKMacOS.sh
        if: runner.os == 'macOS'
      - name: Install PlaydateSDK (Linux)
        run: ./scripts/installSDKLinux.sh
        if: runner.os == 'Linux'
      - name: Run tests (Linux)
        run: xvfb-run -a yarn test:ci
        if: runner.os == 'Linux'
      - name: Run tests
        run: yarn test:ci
        if: runner.os != 'Linux'
